name: Pipeline ELT y Modelo Cuantitativo

on:
  schedule:
    - cron: '*/15 14-20 * * 1-5'
  workflow_dispatch:

jobs:
  ejecutar-arquitectura:
    runs-on: ubuntu-latest
    
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar entorno Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip' # Acelera las ejecuciones futuras cacheando dependencias

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: Crear credencial GCP temporal
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' > gcp-key.json

      - name: Configurar dbt profiles dinámico
        run: |
          mkdir -p ~/.dbt
          cat << EOF > ~/.dbt/profiles.yml
          portfolio_finanzas:
            target: dev
            outputs:
              dev:
                type: bigquery
                method: service-account
                project: portfolio-analytics-eng
                dataset: mercado_financiero_dev
                threads: 4
                location: US
                keyfile: $(pwd)/gcp-key.json
          EOF

      - name: Ejecutar Capa de Transformación (dbt run)
        run: |
          dbt run --project-dir portfolio_finanzas

      - name: Ejecutar Data Quality (dbt test)
        run: |
          dbt test --project-dir portfolio_finanzas

      - name: Ejecutar Motor Cuantitativo (Python)
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          python analytics/modelos_cuantitativos.py
